#!/usr/bin/env python
import random
import sys

def check(key):
	sum = 0
	for c in key:
		sum += ord(c)
	return sum

cracked = False
if len(sys.argv) >= 3:
	if sys.argv[1] == "normal":
		key = ""
		while not cracked:	
			key += random.choice("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$%^&*()_+{[]|\:\'\",<.>/?`~\\ ")
			sum = check(key)
			if '0x' not in sys.argv[2]:
				if sum > int(sys.argv[2]):
					key = ""
				elif sum == int(sys.argv[2]):
					print "Found normal key: " + key
					cracked = True
			else:
				if sum > int(sys.argv[2], 16):
					key = ""
				elif sum == int(sys.argv[2], 16):
					print "Found normal key: " + key
					cracked = True
	if sys.argv[1] == "leet":
		key = "1337"
		while not cracked:	
			key += random.choice("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$%^&*()_+{[]|\:\'\",<.>/?`~\\ ")
			sum = check(key)
			if '0x' not in sys.argv[2]:
				if sum > int(sys.argv[2]):
					key = "1337"
				elif sum == int(sys.argv[2]):
					print "Found leet key: " + key
					cracked = True
			else:
				if sum > int(sys.argv[2], 16):
					key = "1337"
				elif sum == int(sys.argv[2], 16):
					print "Found leet key: " + key
					cracked = True
	if sys.argv[1] == "extra-leet":
		key = "1337x1337"
		while not cracked:	
			key += random.choice("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$%^&*()_+{[]|\:\'\",<.>/?`~\\ ")
			sum = check(key)
			if '0x' not in sys.argv[2]:
				if sum > int(sys.argv[2]):
					key = "1337x1337"
				elif sum == int(sys.argv[2]):
					print "Found extra-leet key: " + key
					cracked = True
			else:
				if sum > int(sys.argv[2], 16):
					key = "1337x1337"
				elif sum == int(sys.argv[2], 16):
					print "Found extra-leet key: " + key
					cracked = True
	if sys.argv[1] == "extreme-leet":
		key = "1337x1337x1337"
		while not cracked:	
			key += random.choice("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$%^&*()_+{[]|\:\'\",<.>/?`~\\ ")
			sum = check(key)
			if '0x' not in sys.argv[2]:
				if sum > int(sys.argv[2]):
					key = "1337x1337x1337"
				elif sum == int(sys.argv[2]):
					print "Found extreme-leet key: " + key
					cracked = True
			else:
				if sum > int(sys.argv[2], 16):
					key = "1337x1337x1337"
				elif sum == int(sys.argv[2], 16):
					print "Found extreme-leet key: " + key
					cracked = True
else:
	if len(sys.argv) == 2:
		print
		print "Usage: ./1337Keys [mode] [hex or dec]"
		print
		print "Modes:"
		print
		print "normal		-		Finds any key"
		print "leet 		-		Only finds keys that begin with 1337"
		print "extra-leet 	-		Only finds keys that begin with 1337x1337"
		print "extreme-leet 	-		Only finds keys that begin with 1337x1337x1337"
		print
		print "Example: ./1337Keys extra-leet 0x302"
		print "Found extra-leet key: 1337x1337ww"
		print
	else:
		print "Usage: ./1337Keys [mode] [hex or dec]"
